name: challenge
on: push

jobs:
  job1:
    name: Print the date on ubuntu
    runs-on: ubuntu-latest
    steps: 
      - name: Step one
        run: date
  job2:
    name: Print the date on windows
    runs-on: windows-latest
    steps: 
      - name: Step one
        run: Get-Date
  job3:
    name: Print the date on macos
    runs-on: macos-latest
    steps: 
      - name: Step one
        run: date
  job4:
    name: Print the date on ubuntu 16
    runs-on: ubuntu-16.04
    needs: [job1, job2, job3]
    steps: 
      - name: Step one
        run: date
        

   